config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    namespace :dashboard do
      resources :cards do
        post 'simple_test', on: :collection
      end

      resources :users, :decks, shallow: true do
        resources :cards
      end

      resources :users do
        member do
          put 'current_deck'
        end
      end
    end

    namespace :home do
      get "logout" => "sessions#destroy", :as => "logout"
      resources :sessions
      post "oauth/callback" => "oauths#callback"
      get "oauth/callback" => "oauths#callback"
      get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
    end

    root 'dashboard/home#index'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cards, dependent: :destroy
  has_many :decks, dependent: :destroy
  has_many :authentications, dependent: :destroy
  belongs_to :current_deck, class_name: "Deck", foreign_key: "current_deck_id"
  before_validation :normalize_email, on: [:create, :edit, :update]

  def current_deck_check
    current_deck ? current_deck.cards.rand_cards.first : cards.rand_cards.first
  end

  def self.pending_cards
    joins(:cards).merge(Card.expired).distinct.find_each do |users|
      NotificationsMailer.notifications_email(users).deliver_now
    end
  end

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  accepts_nested_attributes_for :authentications

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email

  private

  def normalize_email
    self.email = email.strip.downcase
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :find_cards, only: [:edit, :update, :destroy, :show, :simple_test]

  def index
    @cards = current_user.cards.all
  end

  def show; end

  def new
    @cards = current_user.cards.new
  end

  def edit; end

  def create
    @cards = current_user.cards.build(cards_params)
    if @cards.save
      redirect_to dashboard_cards_path
    else
      render 'new'
    end
  end

  def update
    if @cards.update(cards_params)
      redirect_to dashboard_cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @cards.destroy

    redirect_to dashboard_cards_path
  end

  def simple_test
    if @cards.check_translation(cards_params[:original_text])
      case @cards.check_typos(cards_params[:original_text])
      when 0 then flash[:notice] = t(:perfect)
      when 1 then flash[:error] = t(:error, correct: @cards.original_text, your: cards_params[:original_text].mb_chars.downcase.titleize)
      else
        flash[:error] = t(:error2, correct: @cards.original_text)
      end
    end
    redirect_to root_url
  end

  private

  def cards_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :avatar, :deck_id)
  end

  def find_cards
    @cards = current_user.cards.find(params[:id])
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :find_decks, only: [:edit, :update, :destroy, :show]

  def index
    @decks = current_user.decks.all
  end

  def new
    @decks = current_user.decks.new
  end

  def create
    @decks = current_user.decks.build(decks_params)
    if @decks.save
      redirect_to dashboard_decks_path
    else
      render :new
    end
  end

  def update
    if @decks.update(decks_params)
      redirect_to dashboard_decks_path
    else
      render 'edit'
    end
  end

  def destroy
    @decks.destroy
    redirect_to dashboard_decks_path
  end

  def edit; end

  def show; end

  private

  def find_decks
    @decks = current_user.decks.find(params[:id])
  end

  def decks_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  before_filter :require_login, only: :secret

  def index
    @card = current_user.current_deck_check if current_user
  end

  def secret; end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :find_users, only: [:edit, :show, :update, :destroy, :current_deck]

  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create
    @users = User.new(users_params)
    if @users.save
      auto_login(@users)
      redirect_to root_url, notice: t(:sign_up)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @users.update(users_params)
      set_locale
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @users.destroy
    redirect_to root_path
  end

  def current_deck
    @users.update_attribute(:current_deck_id, params[:id])
    redirect_to dashboard_decks_path
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :locale)
  end

  def find_users
    @users = User.find(current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_users, only: [:edit, :show, :update, :destroy, :current_deck]

  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create
    @users = User.new(users_params)
    if @users.save
      auto_login(@users)
      redirect_to root_url, notice: t(:sign_up)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @users.update(users_params)
      set_locale
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @users.destroy
    redirect_to root_path
  end

  def current_deck
    @users.update_attribute(:current_deck_id, params[:id])
    redirect_to decks_path
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :locale)
  end

  def find_users
    @users = User.find(current_user.id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/users/_add_user_form.html.erb
<%= simple_form_for [:dashboard, @users] do |f| %>
  <% if @users.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @users.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <b><%= t(:email) %></b><%= f.input_field :email %>
  <b><%= t(:password) %></b><%= f.password_field :password %>
  <% unless @users.new_record? %>
    <%= f.input :locale, collection: I18n.available_locales %>
  <% end%>
  <%= f.button :submit, class: 'btn btn-default'%>
<% end %>

app/views/dashboard/users/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t(:edit_profile) %></h4>
	</div>
</div>
<%= render 'add_user_form'%>

app/views/dashboard/users/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t(:registration)%></h4>
	</div>
</div>
<%= render 'add_user_form'%>
<h4><%= t(:social)%></h4>
<%= link_to image_tag("facebook.png", :border => 0, :alt => '', :width => 30, :height => 30, :title => ''), home_auth_at_provider_path(:provider => :facebook) %>
<%= link_to image_tag("VK.png", :border => 0, :alt => '', :width => 30, :height => 30, :title => ''), home_auth_at_provider_path(:provider => :vk) %>

app/views/dashboard/users/show.html.erb
<table class="table">
 	<div class="panel panel-default">

  	<div class="panel-heading"><h4><%= @users.email %></h4>
   		<tr>
   	 		<td><b><%= t(:email)%></td>
        <td><b><%= t(:current_deck)%></td>
        <td></td>
        <td></td>
    	</tr>
		</div>
  		<tr>
  		  <td><%= @users.email %></td>
        <% @users.decks.each do |decks| %>
        <% if current_user.current_deck_id == decks.id %>
        <td><%= decks.name %></td>
        <% end %>
        <% end %>
        <td></td>
        <td><%= link_to t(:edit), edit_dashboard_user_path(@users) %></td>
        <td><%= link_to t(:delete), dashboard_user_path(@users),
                method: :delete,
                data: { confirm: 'Вы уверены, что хотите удалить?' } %></td>
  		</tr>
	</div>
</table>