config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    namespace :dashboard do
      resources :cards do
        post 'simple_test', on: :collection
      end

      resources :users, :decks, shallow: true do
        resources :cards
      end

      resources :users do
        member do
          put 'current_deck'
        end
      end
    end

    namespace :home do
      get "logout" => "sessions#destroy", :as => "logout"
      resources :sessions
      post "oauth/callback" => "oauths#callback"
      get "oauth/callback" => "oauths#callback"
      get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
    end

    root 'dashboard/home#index'
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards, dependent: :destroy
  belongs_to :user
  before_validation :normalize_deck, on: [:create, :edit, :update]
  validates :name, presence: true,
                uniqueness: { confirmation: true }

  def normalize_deck
    self.name = name.mb_chars.downcase
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :find_decks, only: [:edit, :update, :destroy, :show]

  def index
    @decks = current_user.decks.all
  end

  def new
    @decks = current_user.decks.new
  end

  def create
    @decks = current_user.decks.build(decks_params)
    if @decks.save
      redirect_to dashboard_decks_path
    else
      render :new
    end
  end

  def update
    if @decks.update(decks_params)
      redirect_to dashboard_decks_path
    else
      render 'edit'
    end
  end

  def destroy
    @decks.destroy
    redirect_to dashboard_decks_path
  end

  def edit; end

  def show; end

  private

  def find_decks
    @decks = current_user.decks.find(params[:id])
  end

  def decks_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :find_decks, only: [:edit, :update, :destroy, :show]

  def index
    @decks = current_user.decks.all
  end

  def new
    @decks = current_user.decks.new
  end

  def create
    @decks = current_user.decks.build(decks_params)
    if @decks.save
      redirect_to decks_url
    else
      render :new
    end
  end

  def update
    if @decks.update(decks_params)
      redirect_to @decks
    else
      render 'edit'
    end
  end

  def destroy
    @decks.destroy
    redirect_to decks_path
  end

  def edit; end

  def show; end

  private

  def find_decks
    @decks = current_user.decks.find(params[:id])
  end

  def decks_params
    params.require(:deck).permit(:name)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_decks_form.html.erb
<%= simple_form_for @decks do |f| %>
  <%= f.input :name, as: :string,
                           required: false %>
  <%= f.button :submit, class: 'btn btn-default'%>
  <% end %>

app/views/decks/index.html.erb
<table class="table">
 	<div class="panel panel-default">

  	<div class="panel-heading"><h4><%= t(:all_decks) %></h4>
   		<tr>
   	 		<td><b><%= t(:name) %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    	</tr>
      <tr></tr>
		</div>
  	<% @decks.each do |decks| %>
  	  <tr>
        <td><%= decks.name %></td>
        <% if current_user.current_deck_id == decks.id %>
  	    <td> <span class="label label-info"><%= t(:current_deck)%></span></td>
        <td></td>
        <% else %>
        <td></td>
        <td><%= link_to t(:make_current), current_deck_user_path(decks), method: :put  %></td>
        <% end %>
        <td><%= link_to t(:show), deck_path(decks) %></td>
        <td><%= link_to t(:edit), edit_deck_path(decks) %></td>
        <td><%= link_to t(:delete), deck_path(decks),
                method: :delete,
                data: { confirm: 'Вы уверены, что хотите удалить?' } %></td>
  	  </tr>
 		<% end %>
	</div>
</table>

app/views/decks/show.html.erb
<table class="table">
 	<div class="panel panel-default">

    <div class="panel-heading"><h4><%= t(:name) %><%= @decks.name %></h4>
   		<tr>
        <td><b><%= t(:name) %></td>
   	 		<td><b><%= t(:original_text) %></td>
   	 		<td><b><%= t(:translated_text) %></td>
   	 		<td><b><%= t(:review_date) %></td>
        <td></td>
        <td></td>
        <td></td>
    	</tr>
		</div>
      <tr>
        <td><%= @decks.name %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
        <% @decks.cards.each do |cards| %>
          <tr>
            <td></td>
            <td><%= cards.original_text %></td>
            <td><%= cards.translated_text %></td>
            <td><%= cards.review_date.strftime("%d.%m.%Y") %></td>
            <td><%= link_to t(:show), card_path(cards) %></td>
            <td><%= link_to t(:edit), edit_card_path(cards) %></td>
            <td><%= link_to t(:delete), card_path(cards),
                    method: :delete,
                    data: { confirm: 'Вы уверены, что хотите удалить?' } %></td>

          </tr>
        <% end %>

	</div>
</table>