config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    namespace :dashboard do
      resources :cards do
        post 'simple_test', on: :collection
      end

      resources :users, :decks, shallow: true do
        resources :cards
      end

      resources :users do
        member do
          put 'current_deck'
        end
      end
    end

    namespace :home do
      get "logout" => "sessions#destroy", :as => "logout"
      resources :sessions
      post "oauth/callback" => "oauths#callback"
      get "oauth/callback" => "oauths#callback"
      get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
    end

    root 'dashboard/home#index'
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards, dependent: :destroy
  belongs_to :user
  before_validation :normalize_deck, on: [:create, :edit, :update]
  validates :name, presence: true,
                uniqueness: { confirmation: true }

  def normalize_deck
    self.name = name.mb_chars.downcase
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :find_cards, only: [:edit, :update, :destroy, :show, :simple_test]

  def index
    @cards = current_user.cards.all
  end

  def show; end

  def new
    @cards = current_user.cards.new
  end

  def edit; end

  def create
    @cards = current_user.cards.build(cards_params)
    if @cards.save
      redirect_to dashboard_cards_path
    else
      render 'new'
    end
  end

  def update
    if @cards.update(cards_params)
      redirect_to dashboard_cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @cards.destroy

    redirect_to dashboard_cards_path
  end

  def simple_test
    if @cards.check_translation(cards_params[:original_text])
      case @cards.check_typos(cards_params[:original_text])
      when 0 then flash[:notice] = t(:perfect)
      when 1 then flash[:error] = t(:error, correct: @cards.original_text, your: cards_params[:original_text].mb_chars.downcase.titleize)
      else
        flash[:error] = t(:error2, correct: @cards.original_text)
      end
    end
    redirect_to root_url
  end

  private

  def cards_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :avatar, :deck_id)
  end

  def find_cards
    @cards = current_user.cards.find(params[:id])
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :find_decks, only: [:edit, :update, :destroy, :show]

  def index
    @decks = current_user.decks.all
  end

  def new
    @decks = current_user.decks.new
  end

  def create
    @decks = current_user.decks.build(decks_params)
    if @decks.save
      redirect_to dashboard_decks_path
    else
      render :new
    end
  end

  def update
    if @decks.update(decks_params)
      redirect_to dashboard_decks_path
    else
      render 'edit'
    end
  end

  def destroy
    @decks.destroy
    redirect_to dashboard_decks_path
  end

  def edit; end

  def show; end

  private

  def find_decks
    @decks = current_user.decks.find(params[:id])
  end

  def decks_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  before_filter :require_login, only: :secret

  def index
    @card = current_user.current_deck_check if current_user
  end

  def secret; end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :find_users, only: [:edit, :show, :update, :destroy, :current_deck]

  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create
    @users = User.new(users_params)
    if @users.save
      auto_login(@users)
      redirect_to root_url, notice: t(:sign_up)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @users.update(users_params)
      set_locale
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @users.destroy
    redirect_to root_path
  end

  def current_deck
    @users.update_attribute(:current_deck_id, params[:id])
    redirect_to dashboard_decks_path
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :locale)
  end

  def find_users
    @users = User.find(current_user.id)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :find_decks, only: [:edit, :update, :destroy, :show]

  def index
    @decks = current_user.decks.all
  end

  def new
    @decks = current_user.decks.new
  end

  def create
    @decks = current_user.decks.build(decks_params)
    if @decks.save
      redirect_to decks_url
    else
      render :new
    end
  end

  def update
    if @decks.update(decks_params)
      redirect_to @decks
    else
      render 'edit'
    end
  end

  def destroy
    @decks.destroy
    redirect_to decks_path
  end

  def edit; end

  def show; end

  private

  def find_decks
    @decks = current_user.decks.find(params[:id])
  end

  def decks_params
    params.require(:deck).permit(:name)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/dashboard/decks/_decks_form.html.erb
<%= simple_form_for [:dashboard, @decks] do |f| %>
  <%= f.input :name, as: :string,
                           required: false %>
  <%= f.button :submit, class: 'btn btn-default'%>
  <% end %>

app/views/dashboard/decks/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t(:edit)%></h4>
	</div>
</div>
<%= render 'decks_form' %>

app/views/dashboard/decks/index.html.erb
<table class="table">
 	<div class="panel panel-default">

  	<div class="panel-heading"><h4><%= t(:all_decks) %></h4>
   		<tr>
   	 		<td><b><%= t(:name) %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    	</tr>
      <tr></tr>
		</div>
  	<% @decks.each do |decks| %>
  	  <tr>
        <td><%= decks.name %></td>
        <% if current_user.current_deck_id == decks.id %>
  	    <td> <span class="label label-info"><%= t(:current_deck)%></span></td>
        <td></td>
        <% else %>
        <td></td>
        <td><%= link_to t(:make_current), current_deck_dashboard_user_path(decks), method: :put  %></td>
        <% end %>
        <td><%= link_to t(:show), dashboard_deck_path(decks) %></td>
        <td><%= link_to t(:edit), edit_dashboard_deck_path(decks) %></td>
        <td><%= link_to t(:delete), dashboard_deck_path(decks),
                method: :delete,
                data: { confirm: 'Вы уверены, что хотите удалить?' } %></td>
  	  </tr>
 		<% end %>
	</div>
</table>

app/views/dashboard/decks/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h4><%= t(:add_deck)%></h4>
	</div>
</div>
<%= render 'decks_form' %>

app/views/dashboard/decks/show.html.erb
<table class="table">
 	<div class="panel panel-default">

    <div class="panel-heading"><h4><%= t(:name) %><%= @decks.name %></h4>
   		<tr>
        <td><b><%= t(:name) %></td>
   	 		<td><b><%= t(:original_text) %></td>
   	 		<td><b><%= t(:translated_text) %></td>
   	 		<td><b><%= t(:review_date) %></td>
        <td></td>
        <td></td>
        <td></td>
    	</tr>
		</div>
      <tr>
        <td><%= @decks.name %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
        <% @decks.cards.each do |cards| %>
          <tr>
            <td></td>
            <td><%= cards.original_text %></td>
            <td><%= cards.translated_text %></td>
            <td><%= cards.review_date.strftime("%d.%m.%Y") %></td>
            <td><%= link_to t(:show), dashboard_card_path(cards) %></td>
            <td><%= link_to t(:edit), edit_dashboard_card_path(cards) %></td>
            <td><%= link_to t(:delete), dashboard_card_path(cards),
                    method: :delete,
                    data: { confirm: 'Вы уверены, что хотите удалить?' } %></td>

          </tr>
        <% end %>

	</div>
</table>