config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do
    namespace :dashboard do
      resources :cards do
        post 'simple_test', on: :collection
      end

      resources :users, :decks, shallow: true do
        resources :cards
      end

      resources :users do
        member do
          put 'current_deck'
        end
      end
    end

    namespace :home do
      get "logout" => "sessions#destroy", :as => "logout"
      resources :sessions
      post "oauth/callback" => "oauths#callback"
      get "oauth/callback" => "oauths#callback"
      get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
    end

    root 'dashboard/home#index'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:tittle) %></title>
    <link rel="stylesheet" href="application.css">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <header class="clearfix">
  <nav>
    <ul class="navigation-links nav nav-tabs " role="tablist">
    	<li  class="active"><h4><%= link_to t(:tittle), root_path %></h4></li>
      <% if current_user %>
      <li class="dropdown">
      <h4><a class="dropdown-toggle" data-toggle="dropdown" href="Колоды"><%= t(:decks)%></a>
        <ul class="dropdown-menu">
          <li><h5><%= link_to t(:all_decks), dashboard_decks_path %></h5></li>
          <li><h5><%= link_to t(:add_deck), new_dashboard_deck_path %></h5></li>
        </ul>
      </li></h4>
      <li class="dropdown">
      <h4><a class="dropdown-toggle" data-toggle="dropdown" href="Карточки"> <%= t(:cards)%> </a>
        <ul class="dropdown-menu">
          <li><h5><%= link_to t(:all_cards), dashboard_cards_path %></h5></li>
          <li><h5><%= link_to t(:add_cards), new_dashboard_card_path %></h5></li>
        </ul>
      </li></h4>
        <li><h4><%= link_to t(:sign_out), home_logout_path %></h4></li>
        <li><h4><%= t(:sign_in_user)%><%= link_to current_user.email, dashboard_user_path(current_user) %></h4></li>
      <% else %>
        <li><h4><%= link_to t(:registration), new_dashboard_user_path %></h4></li>
        <li><h4><%= link_to t(:sign_in), new_home_session_path %></h4></li>
        <%= link_to image_tag("ru.png", :border => 0, :alt => '', :width => 30, :height => 20, :title => ''), :locale => :ru %>
        <%= link_to image_tag("en.png", :border => 0, :alt => '', :width => 40, :height => 30, :title => ''), :locale => :en %>
      <% end %>
    </ul>
  </nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>